# configs/system.yaml
openai_api_key: "your-api-key-here"
default_model: "gpt-4"
request_timeout: 60
max_tokens: 2000
docker_image: "python:3.9-slim"
container_memory_limit: "512m"
container_cpu_limit: 0.5
workspace_dir: "workspace"
max_agents: 10
agent_timeout: 300
max_retries: 3
log_level: "INFO"
log_file: "system.log"
max_log_size: 10000000
backup_count: 5