# configs/ui.yaml
window_width: 1920
window_height: 1080
window_title: "Multi-Agent System Monitor"
metrics_update_interval: 1.0
node_update_interval: 0.1
max_messages: 1000
max_history: 100
theme: "dark"
agent_colors:
  Research: [0, 150, 255, 255]
  Code: [0, 255, 150, 255]
  Viz: [255, 150, 0, 255]
  QA: [255, 0, 150, 255]
  PM: [150, 0, 255, 255]