agent_timeout: 300
backup_count: 5
config_name: system
container_cpu_limit: 0.5
container_memory_limit: 512m
default_model: gpt-4
docker_image: python:3.9-slim
log_file: system.log
log_level: INFO
max_agents: 10
max_log_size: 10000000
max_retries: 3
max_tokens: 2000
openai_api_key: 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
request_timeout: 60
version: 1.0.0
workspace_dir: workspace
